Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"
  config.vm.hostname = "sensu-centos"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "shell",
    path: "sensu-centos.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end
end
