---
version: "3"
services:
  sensu-backend:
    build:
      context: docker/sensu-backend/
      dockerfile: Dockerfile.debian
    image: sensu-backend:latest
    ports:
    - 3000:3000
    - 8080:8080
    - 8081:8081
    volumes:
    - "./config/sensu/backend.yml:/etc/sensu/backend.yml"
    - "sensu-backend-data:/var/lib/sensu/etcd"
    command: "sensu-backend start --log-level debug"

  sensu-agent:
    build:
      context: docker/sensu-agent/
      dockerfile: Dockerfile.debian
    image: sensu-agent:latest
    volumes:
    - "./config/sensu/agent.yml:/etc/sensu/agent.yml"
    depends_on:
    - sensu-backend
    command: "sensu-agent start --backend-url ws://sensu-backend:8081 --log-level debug"

  influxdb:
    image: influxdb:1.7.7
    ports:
    - 8086:8086
    volumes:
    - "influxdb-data:/var/lib/influxdb"
    - "./config/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf"
    environment:
      INFLUXDB_DB: sensu
    depends_on:
    - sensu-backend # not actually true; only used for demo purposes
    command: influxd

  grafana:
    image: grafana/grafana:5.1.0
    ports:
    - 3001:3000
    volumes:
    - "./config/grafana/provisioning/datasources/influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml"
    - "./config/grafana/provisioning/dashboards/sensu.yaml:/etc/grafana/provisioning/dashboards/sensu.yaml"
    - "./config/grafana/dashboards:/var/lib/grafana/dashboards"
    depends_on:
    - influxdb

volumes:
  sensu-backend-data:
    driver: local
  influxdb-data:
    driver: local
