---
version: "3"
services:
  sensu-backend:
    build:
      context: docker/sensu-backend/
      dockerfile: Dockerfile.debian
    image: sensu-backend:latest
    ports:
    - 3000:3000
    - 8080:8080
    - 8081:8081
    volumes:
    - "./config/sensu/backend.yml:/etc/sensu/backend.yml"
    - "sensu-backend-data:/var/lib/sensu/etcd"
    command: "sensu-backend start --log-level debug"

  sensu-agent:
    build:
      context: docker/sensu-agent/
      dockerfile: Dockerfile.debian
    image: sensu-agent:latest
    volumes:
    - "./config/sensu/agent.yml:/etc/sensu/agent.yml"
    depends_on:
    - sensu-backend
    command: "sensu-agent start --backend-url ws://sensu-backend:8081 --log-level debug"

  sensu-asset-server:
    image: nginx:latest
    ports:
    - 8000:80
    volumes:
    - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    - "./assets:/usr/share/nginx/html/assets"
    depends_on:
    - sensu-backend # not actually true; only used for demo purposes

volumes:
  sensu-backend-data:
    driver: local
